# Generated by Django 5.1 on 2024-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience',
            field=models.IntegerField(default=3, help_text='Years of experience'),
        ),
    ]
